# language is set to c to work around travis ci bug
# https://github.com/travis-ci/travis-ci/issues/2312
language: c
sudo: false
os:
  - linux
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
compiler:
  - clang
  - gcc
env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.3
  - TRAVIS_PYTHON_VERSION=3.4
  - TRAVIS_PYTHON_VERSION=3.5
notifications:
  email:
    recipients:
      - stan-buildbot@googlegroups.com
    on_success: change
    on_failure: always
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
